# Generated by Django 4.2.6 on 2023-11-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tcp_full', 'Nmap TCP Port Scan'), ('udp_quick', 'Nmap UDP Port Scan'), ('vulnerability_custom', 'OpenVAS Network Vulnerability Scan'), ('zap_passive_custom', 'OWASP ZAP Passive Web Application Scan'), ('zap_active_custom', 'OWASP ZAP Active Web Application Scan'), ('ssl_custom', 'Sslyze TLS/SSL Security Scan')], max_length=50)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'SUCCEEDED'), ('error', 'Error')], max_length=50)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='dashboard.scan')),
            ],
        ),
    ]
