# Generated by Django 4.2.6 on 2023-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='openvas_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
